apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: venture-studio-production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: backend

commonLabels:
  environment: production

images:
  - name: venture-studio/backend
    newTag: latest
  - name: venture-studio/frontend
    newTag: latest
