apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: venture-studio-staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend

commonLabels:
  environment: staging

images:
  - name: venture-studio/backend
    newTag: staging
  - name: venture-studio/frontend
    newTag: staging
